<?php
/**
 * SaaS PHP Application Installer
 * Web-based installation wizard for shared hosting
 */

session_start();

// Installation steps
$steps = [
    1 => 'Requirements Check',
    2 => 'Database Configuration',
    3 => 'Application Setup',
    4 => 'Create Admin Account',
    5 => 'Complete'
];

$currentStep = isset($_GET['step']) ? (int)$_GET['step'] : 1;
$error = '';
$success = '';

// Check if already installed
if (file_exists(__DIR__ . '/../config/config.local.php') && $currentStep < 5) {
    header('Location: ?step=5');
    exit;
}

// Handle form submissions
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    switch ($currentStep) {
        case 2: // Database configuration
            $dbHost = trim($_POST['db_host'] ?? 'localhost');
            $dbName = trim($_POST['db_name'] ?? '');
            $dbUser = trim($_POST['db_user'] ?? '');
            $dbPass = $_POST['db_pass'] ?? '';

            // Test connection
            try {
                $pdo = new PDO(
                    "mysql:host={$dbHost}",
                    $dbUser,
                    $dbPass,
                    [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
                );

                // Create database if not exists
                $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
                $pdo->exec("USE `{$dbName}`");

                // Import schema
                $schema = file_get_contents(__DIR__ . '/schema.sql');
                $pdo->exec($schema);

                // Store in session for next step
                $_SESSION['install'] = [
                    'db_host' => $dbHost,
                    'db_name' => $dbName,
                    'db_user' => $dbUser,
                    'db_pass' => $dbPass
                ];

                header('Location: ?step=3');
                exit;
            } catch (PDOException $e) {
                $error = 'Database connection failed: ' . $e->getMessage();
            }
            break;

        case 3: // Application setup
            $appName = trim($_POST['app_name'] ?? 'SaaS App');
            $appUrl = trim($_POST['app_url'] ?? '');
            $authSecret = bin2hex(random_bytes(32));

            $_SESSION['install']['app_name'] = $appName;
            $_SESSION['install']['app_url'] = rtrim($appUrl, '/');
            $_SESSION['install']['auth_secret'] = $authSecret;
            $_SESSION['install']['stripe_secret'] = trim($_POST['stripe_secret'] ?? '');
            $_SESSION['install']['stripe_public'] = trim($_POST['stripe_public'] ?? '');
            $_SESSION['install']['stripe_webhook'] = trim($_POST['stripe_webhook'] ?? '');

            header('Location: ?step=4');
            exit;
            break;

        case 4: // Create admin account
            $email = trim($_POST['admin_email'] ?? '');
            $password = $_POST['admin_password'] ?? '';
            $name = trim($_POST['admin_name'] ?? '');

            if (strlen($password) < 8) {
                $error = 'Password must be at least 8 characters';
                break;
            }

            try {
                $install = $_SESSION['install'];

                $pdo = new PDO(
                    "mysql:host={$install['db_host']};dbname={$install['db_name']};charset=utf8mb4",
                    $install['db_user'],
                    $install['db_pass'],
                    [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
                );

                // Create admin user
                $passwordHash = password_hash($password, PASSWORD_BCRYPT, ['cost' => 10]);

                $stmt = $pdo->prepare("INSERT INTO users (name, email, password_hash, role) VALUES (?, ?, ?, 'owner')");
                $stmt->execute([$name, $email, $passwordHash]);
                $userId = $pdo->lastInsertId();

                // Create team
                $stmt = $pdo->prepare("INSERT INTO teams (name) VALUES (?)");
                $stmt->execute([$email . "'s Team"]);
                $teamId = $pdo->lastInsertId();

                // Add user to team
                $stmt = $pdo->prepare("INSERT INTO team_members (user_id, team_id, role) VALUES (?, ?, 'owner')");
                $stmt->execute([$userId, $teamId]);

                // Generate config file
                $config = <<<PHP
<?php
// Generated by installer on {$date}

// Database
define('DB_HOST', '{$install['db_host']}');
define('DB_NAME', '{$install['db_name']}');
define('DB_USER', '{$install['db_user']}');
define('DB_PASS', '{$install['db_pass']}');

// Application
define('APP_NAME', '{$install['app_name']}');
define('APP_URL', '{$install['app_url']}');
define('APP_ENV', 'production');
define('APP_DEBUG', false);

// Authentication
define('AUTH_SECRET', '{$install['auth_secret']}');

// Stripe (Optional)
define('STRIPE_SECRET_KEY', '{$install['stripe_secret']}');
define('STRIPE_PUBLISHABLE_KEY', '{$install['stripe_public']}');
define('STRIPE_WEBHOOK_SECRET', '{$install['stripe_webhook']}');
PHP;

                $date = date('Y-m-d H:i:s');
                $config = str_replace('{$date}', $date, $config);

                file_put_contents(__DIR__ . '/../config/config.local.php', $config);

                // Clear session
                unset($_SESSION['install']);

                header('Location: ?step=5');
                exit;
            } catch (Exception $e) {
                $error = 'Failed to create admin account: ' . $e->getMessage();
            }
            break;
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Install - SaaS PHP Application</title>
    <style>
        * { box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.5;
            margin: 0;
            padding: 20px;
            background: #f3f4f6;
            min-height: 100vh;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
        }
        .card {
            background: white;
            border-radius: 8px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            padding: 24px;
            margin-bottom: 20px;
        }
        h1 { margin: 0 0 24px; font-size: 24px; }
        h2 { margin: 0 0 16px; font-size: 18px; }
        .steps {
            display: flex;
            justify-content: space-between;
            margin-bottom: 24px;
        }
        .step {
            flex: 1;
            text-align: center;
            padding: 8px;
            font-size: 12px;
            color: #6b7280;
        }
        .step.active {
            color: #ea580c;
            font-weight: 600;
        }
        .step.completed {
            color: #10b981;
        }
        label {
            display: block;
            margin-bottom: 4px;
            font-weight: 500;
            font-size: 14px;
        }
        input, select {
            width: 100%;
            padding: 10px 12px;
            border: 1px solid #d1d5db;
            border-radius: 6px;
            font-size: 14px;
            margin-bottom: 16px;
        }
        input:focus {
            outline: none;
            border-color: #ea580c;
        }
        button {
            background: #ea580c;
            color: white;
            border: none;
            padding: 12px 24px;
            border-radius: 6px;
            font-size: 14px;
            font-weight: 600;
            cursor: pointer;
            width: 100%;
        }
        button:hover { background: #c2410c; }
        .error {
            background: #fef2f2;
            border: 1px solid #fecaca;
            color: #dc2626;
            padding: 12px;
            border-radius: 6px;
            margin-bottom: 16px;
            font-size: 14px;
        }
        .success {
            background: #ecfdf5;
            border: 1px solid #a7f3d0;
            color: #047857;
            padding: 12px;
            border-radius: 6px;
            margin-bottom: 16px;
            font-size: 14px;
        }
        .check {
            color: #10b981;
            margin-right: 8px;
        }
        .fail {
            color: #dc2626;
            margin-right: 8px;
        }
        .requirement {
            padding: 8px 0;
            border-bottom: 1px solid #e5e7eb;
            font-size: 14px;
        }
        .hint {
            font-size: 12px;
            color: #6b7280;
            margin-top: -12px;
            margin-bottom: 16px;
        }
        a {
            color: #ea580c;
            text-decoration: none;
        }
        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <h1>SaaS PHP Installer</h1>

            <div class="steps">
                <?php foreach ($steps as $num => $name): ?>
                <div class="step <?= $num < $currentStep ? 'completed' : ($num === $currentStep ? 'active' : '') ?>">
                    <?= $num ?>. <?= $name ?>
                </div>
                <?php endforeach; ?>
            </div>

            <?php if ($error): ?>
            <div class="error"><?= htmlspecialchars($error) ?></div>
            <?php endif; ?>

            <?php if ($currentStep === 1): ?>
            <!-- Requirements Check -->
            <h2>System Requirements</h2>
            <?php
            $requirements = [
                'PHP Version >= 7.4' => version_compare(PHP_VERSION, '7.4.0', '>='),
                'PDO Extension' => extension_loaded('pdo'),
                'PDO MySQL Driver' => extension_loaded('pdo_mysql'),
                'JSON Extension' => extension_loaded('json'),
                'cURL Extension' => extension_loaded('curl'),
                'Config directory writable' => is_writable(__DIR__ . '/../config')
            ];
            $allPassed = true;
            foreach ($requirements as $name => $passed):
                if (!$passed) $allPassed = false;
            ?>
            <div class="requirement">
                <span class="<?= $passed ? 'check' : 'fail' ?>"><?= $passed ? '✓' : '✗' ?></span>
                <?= $name ?>
            </div>
            <?php endforeach; ?>

            <?php if ($allPassed): ?>
            <br>
            <a href="?step=2"><button type="button">Continue</button></a>
            <?php else: ?>
            <br>
            <div class="error">Please fix the requirements above before continuing.</div>
            <?php endif; ?>

            <?php elseif ($currentStep === 2): ?>
            <!-- Database Configuration -->
            <h2>Database Configuration</h2>
            <form method="POST">
                <label for="db_host">Database Host</label>
                <input type="text" name="db_host" id="db_host" value="localhost" required>

                <label for="db_name">Database Name</label>
                <input type="text" name="db_name" id="db_name" required placeholder="saas_app">
                <p class="hint">The database will be created if it doesn't exist.</p>

                <label for="db_user">Database Username</label>
                <input type="text" name="db_user" id="db_user" required>

                <label for="db_pass">Database Password</label>
                <input type="password" name="db_pass" id="db_pass">

                <button type="submit">Test Connection & Create Tables</button>
            </form>

            <?php elseif ($currentStep === 3): ?>
            <!-- Application Setup -->
            <h2>Application Setup</h2>
            <form method="POST">
                <label for="app_name">Application Name</label>
                <input type="text" name="app_name" id="app_name" value="SaaS App" required>

                <label for="app_url">Application URL</label>
                <input type="url" name="app_url" id="app_url" required placeholder="https://yourdomain.com">
                <p class="hint">Full URL without trailing slash.</p>

                <h3 style="margin-top: 24px; font-size: 16px;">Stripe Configuration (Optional)</h3>

                <label for="stripe_secret">Stripe Secret Key</label>
                <input type="text" name="stripe_secret" id="stripe_secret" placeholder="sk_live_...">

                <label for="stripe_public">Stripe Publishable Key</label>
                <input type="text" name="stripe_public" id="stripe_public" placeholder="pk_live_...">

                <label for="stripe_webhook">Stripe Webhook Secret</label>
                <input type="text" name="stripe_webhook" id="stripe_webhook" placeholder="whsec_...">

                <button type="submit">Continue</button>
            </form>

            <?php elseif ($currentStep === 4): ?>
            <!-- Create Admin Account -->
            <h2>Create Admin Account</h2>
            <form method="POST">
                <label for="admin_name">Name</label>
                <input type="text" name="admin_name" id="admin_name" required>

                <label for="admin_email">Email</label>
                <input type="email" name="admin_email" id="admin_email" required>

                <label for="admin_password">Password</label>
                <input type="password" name="admin_password" id="admin_password" required minlength="8">
                <p class="hint">Minimum 8 characters.</p>

                <button type="submit">Create Account & Finish</button>
            </form>

            <?php elseif ($currentStep === 5): ?>
            <!-- Complete -->
            <h2>Installation Complete!</h2>
            <div class="success">
                Your SaaS application has been installed successfully.
            </div>

            <p>Next steps:</p>
            <ul style="padding-left: 20px; font-size: 14px;">
                <li>Delete or protect the <code>/install</code> directory</li>
                <li>Configure your web server to point to <code>/public</code></li>
                <li>Set up Stripe webhooks if using payments</li>
            </ul>

            <br>
            <a href="../public/"><button type="button">Go to Application</button></a>

            <?php endif; ?>
        </div>
    </div>
</body>
</html>
